-- seed.sql
-- Realistic San Pedro en Bus seed data: two routes (SAN_RAMON, LA_EUROPA) are
-- visibly worse than the rest, units vary between short numbers and plates, a
-- meaningful share of reports carry no unit, problems spread across all five
-- informal categories (reliability, stops, safety, comfort, conduct/noise), and
-- reports span the last ~30 days including several multi-problem reports.

insert into public.reports (route, unit, problems, created_at) values
  ('BARRIO_PINTO', null, array['hacinados'], now() - interval '21 hours 36 minutes'),
  ('SAN_RAMON', null, array['acoso'], now() - interval '42 hours 2 minutes'),
  ('SAN_RAMON', '62', array['pasajero_sin_audifonos'], now() - interval '45 hours 35 minutes'),
  ('BARRIO_PINTO', null, array['horario_sin_servicio', 'hacinados'], now() - interval '49 hours 24 minutes'),
  ('LA_EUROPA', null, array['no_hizo_parada', 'paro_otro_lado'], now() - interval '61 hours 35 minutes'),
  ('GRANADILLA', '51', array['horario_sin_servicio', 'olia_mal_sucio'], now() - interval '64 hours 7 minutes'),
  ('SABANILLA', '91', array['pasajero_violento', 'olia_mal_sucio'], now() - interval '67 hours 17 minutes'),
  ('LA_EUROPA', '99', array['duro_toda_la_vida'], now() - interval '67 hours 44 minutes'),
  ('LA_EUROPA', '18', array['paro_otro_lado'], now() - interval '81 hours 31 minutes'),
  ('LA_EUROPA', null, array['pasajero_violento', 'chofer_trato_mal', 'volumen_molesto'], now() - interval '86 hours 7 minutes'),
  ('LA_EUROPA', '41', array['paro_otro_lado', 'insegura_parada'], now() - interval '89 hours 3 minutes'),
  ('SABANILLA', '51', array['no_paso_google_maps', 'conduccion_temeraria'], now() - interval '115 hours 55 minutes'),
  ('CEDROS', null, array['no_horario_claro', 'paro_otro_lado'], now() - interval '122 hours 47 minutes'),
  ('SAN_RAMON', '91', array['horario_sin_servicio'], now() - interval '154 hours 47 minutes'),
  ('SALITRILLOS', null, array['duro_toda_la_vida', 'pasajero_sin_audifonos'], now() - interval '154 hours 57 minutes'),
  ('BARRIO_PINTO', 'SJB123', array['hacinados', 'pasajero_sin_audifonos'], now() - interval '157 hours 1 minutes'),
  ('LA_CAMPINA', '24', array['pasajero_sin_audifonos'], now() - interval '162 hours 20 minutes'),
  ('LA_EUROPA', '12', array['no_horario_claro', 'no_hizo_parada', 'volumen_molesto'], now() - interval '166 hours 55 minutes'),
  ('CEDROS', '58', array['acoso'], now() - interval '171 hours 7 minutes'),
  ('LA_EUROPA', 'SPB045', array['pasajero_violento', 'cucarachas'], now() - interval '173 hours 10 minutes'),
  ('LA_CAMPINA', null, array['insegura_parada', 'chofer_trato_mal'], now() - interval '176 hours 17 minutes'),
  ('SALITRILLOS', 'SJ0912', array['paro_otro_lado', 'hacinados'], now() - interval '184 hours 0 minutes'),
  ('SAN_RAMON', 'SJ0912', array['pasajero_sin_audifonos'], now() - interval '198 hours 59 minutes'),
  ('LA_EUROPA', '84', array['no_hizo_parada', 'hacinados', 'pasajero_sin_audifonos'], now() - interval '199 hours 48 minutes'),
  ('BARRIO_PINTO', '24', array['chofer_trato_mal'], now() - interval '202 hours 26 minutes'),
  ('LA_CAMPINA', null, array['no_hizo_parada', 'acoso'], now() - interval '202 hours 48 minutes'),
  ('LA_EUROPA', '62', array['no_paso_google_maps', 'no_hizo_parada', 'hacinados'], now() - interval '205 hours 55 minutes'),
  ('SABANILLA', '33', array['acoso', 'chofer_trato_mal'], now() - interval '215 hours 56 minutes'),
  ('LA_CAMPINA', null, array['no_hizo_parada', 'paro_otro_lado'], now() - interval '226 hours 25 minutes'),
  ('SABANILLA', 'BUS217', array['volumen_molesto'], now() - interval '237 hours 49 minutes'),
  ('SAN_RAMON', 'SJ0912', array['hacinados'], now() - interval '245 hours 15 minutes'),
  ('SALITRILLOS', 'BUS217', array['chofer_trato_mal'], now() - interval '249 hours 27 minutes'),
  ('VARGAS_ARAYA', 'CR4521', array['cucarachas'], now() - interval '272 hours 13 minutes'),
  ('GRANADILLA', 'SJ0912', array['no_horario_claro', 'volumen_molesto'], now() - interval '276 hours 33 minutes'),
  ('SALITRILLOS', 'SJB123', array['paro_otro_lado', 'olia_mal_sucio'], now() - interval '286 hours 8 minutes'),
  ('SABANILLA', null, array['duro_toda_la_vida', 'no_hizo_parada'], now() - interval '304 hours 23 minutes'),
  ('LA_EUROPA', 'SPB045', array['hacinados'], now() - interval '305 hours 21 minutes'),
  ('VARGAS_ARAYA', '91', array['no_paso_google_maps', 'no_hizo_parada'], now() - interval '315 hours 15 minutes'),
  ('LA_EUROPA', 'CR4521', array['no_horario_claro'], now() - interval '321 hours 55 minutes'),
  ('VARGAS_ARAYA', 'BUS217', array['paro_otro_lado'], now() - interval '323 hours 53 minutes'),
  ('SAN_RAMON', 'SJB123', array['cucarachas'], now() - interval '345 hours 57 minutes'),
  ('LA_EUROPA', '77', array['no_paso_google_maps', 'pasajero_violento'], now() - interval '347 hours 16 minutes'),
  ('LA_CAMPINA', null, array['hacinados', 'olia_mal_sucio'], now() - interval '357 hours 12 minutes'),
  ('SAN_RAMON', null, array['conduccion_temeraria', 'cucarachas'], now() - interval '358 hours 22 minutes'),
  ('GRANADILLA', 'BUS217', array['no_hizo_parada', 'paro_otro_lado'], now() - interval '360 hours 40 minutes'),
  ('SAN_RAMON', 'BUS217', array['insegura_parada'], now() - interval '361 hours 10 minutes'),
  ('LA_EUROPA', 'CR4521', array['duro_toda_la_vida', 'insegura_parada'], now() - interval '384 hours 38 minutes'),
  ('LA_CAMPINA', '84', array['chofer_trato_mal', 'volumen_molesto'], now() - interval '385 hours 24 minutes'),
  ('LA_EUROPA', '18', array['paro_otro_lado'], now() - interval '409 hours 28 minutes'),
  ('VARGAS_ARAYA', '62', array['no_horario_claro'], now() - interval '411 hours 24 minutes'),
  ('SAN_RAMON', '91', array['hacinados'], now() - interval '416 hours 59 minutes'),
  ('CEDROS', '84', array['conduccion_temeraria', 'chofer_trato_mal'], now() - interval '424 hours 15 minutes'),
  ('SAN_RAMON', '62', array['insegura_parada', 'olia_mal_sucio'], now() - interval '425 hours 15 minutes'),
  ('GRANADILLA', null, array['no_paso_google_maps', 'pasajero_violento'], now() - interval '426 hours 7 minutes'),
  ('SABANILLA', null, array['insegura_parada', 'volumen_molesto'], now() - interval '432 hours 13 minutes'),
  ('LA_EUROPA', '58', array['pasajero_violento'], now() - interval '436 hours 48 minutes'),
  ('VARGAS_ARAYA', 'SJ0912', array['paro_otro_lado'], now() - interval '438 hours 32 minutes'),
  ('SALITRILLOS', null, array['pasajero_violento'], now() - interval '450 hours 52 minutes'),
  ('LA_EUROPA', '18', array['olia_mal_sucio'], now() - interval '463 hours 52 minutes'),
  ('CEDROS', 'CR4521', array['horario_sin_servicio', 'conduccion_temeraria'], now() - interval '468 hours 41 minutes'),
  ('SAN_RAMON', null, array['horario_sin_servicio', 'conduccion_temeraria'], now() - interval '474 hours 8 minutes'),
  ('SABANILLA', null, array['pasajero_sin_audifonos'], now() - interval '474 hours 35 minutes'),
  ('SAN_RAMON', null, array['no_horario_claro', 'pasajero_violento', 'conduccion_temeraria'], now() - interval '477 hours 20 minutes'),
  ('LA_CAMPINA', '18', array['no_hizo_parada'], now() - interval '484 hours 5 minutes'),
  ('LA_CAMPINA', null, array['no_hizo_parada', 'cucarachas', 'olia_mal_sucio'], now() - interval '499 hours 14 minutes'),
  ('SABANILLA', '41', array['pasajero_violento'], now() - interval '502 hours 7 minutes'),
  ('CEDROS', '77', array['cucarachas', 'volumen_molesto'], now() - interval '503 hours 46 minutes'),
  ('SAN_RAMON', 'SPB045', array['pasajero_violento', 'hacinados'], now() - interval '507 hours 42 minutes'),
  ('LA_EUROPA', 'TCR889', array['no_hizo_parada', 'cucarachas'], now() - interval '512 hours 48 minutes'),
  ('LA_CAMPINA', 'SJB123', array['paro_otro_lado'], now() - interval '530 hours 47 minutes'),
  ('LA_EUROPA', 'SPB045', array['olia_mal_sucio', 'volumen_molesto'], now() - interval '533 hours 18 minutes'),
  ('LA_EUROPA', '12', array['hacinados'], now() - interval '534 hours 42 minutes'),
  ('GRANADILLA', 'SPB045', array['pasajero_violento'], now() - interval '546 hours 18 minutes'),
  ('VARGAS_ARAYA', null, array['no_paso_google_maps'], now() - interval '552 hours 51 minutes'),
  ('SALITRILLOS', 'TCR889', array['horario_sin_servicio', 'olia_mal_sucio'], now() - interval '571 hours 2 minutes'),
  ('SAN_RAMON', null, array['cucarachas'], now() - interval '572 hours 6 minutes'),
  ('SABANILLA', '51', array['horario_sin_servicio', 'no_hizo_parada'], now() - interval '573 hours 51 minutes'),
  ('SABANILLA', null, array['no_hizo_parada', 'paro_otro_lado'], now() - interval '580 hours 19 minutes'),
  ('CEDROS', null, array['duro_toda_la_vida', 'hacinados'], now() - interval '588 hours 20 minutes'),
  ('LA_CAMPINA', '77', array['no_paso_google_maps', 'pasajero_sin_audifonos'], now() - interval '591 hours 22 minutes'),
  ('SALITRILLOS', '91', array['olia_mal_sucio'], now() - interval '592 hours 13 minutes'),
  ('SAN_RAMON', null, array['no_horario_claro', 'pasajero_sin_audifonos'], now() - interval '594 hours 39 minutes'),
  ('SAN_RAMON', null, array['cucarachas'], now() - interval '597 hours 59 minutes'),
  ('SAN_RAMON', null, array['olia_mal_sucio'], now() - interval '611 hours 41 minutes'),
  ('BARRIO_PINTO', '58', array['conduccion_temeraria'], now() - interval '614 hours 16 minutes'),
  ('GRANADILLA', null, array['paro_otro_lado', 'chofer_trato_mal'], now() - interval '627 hours 5 minutes'),
  ('VARGAS_ARAYA', null, array['conduccion_temeraria', 'pasajero_sin_audifonos'], now() - interval '650 hours 8 minutes'),
  ('SAN_RAMON', 'SJ0912', array['acoso', 'hacinados'], now() - interval '660 hours 18 minutes'),
  ('CEDROS', null, array['no_hizo_parada'], now() - interval '661 hours 58 minutes'),
  ('SABANILLA', '77', array['volumen_molesto'], now() - interval '665 hours 16 minutes'),
  ('BARRIO_PINTO', null, array['paro_otro_lado', 'olia_mal_sucio', 'pasajero_sin_audifonos'], now() - interval '669 hours 24 minutes'),
  ('SAN_RAMON', null, array['pasajero_violento'], now() - interval '671 hours 33 minutes'),
  ('SALITRILLOS', '33', array['acoso', 'cucarachas'], now() - interval '677 hours 39 minutes'),
  ('LA_CAMPINA', '99', array['horario_sin_servicio', 'volumen_molesto'], now() - interval '679 hours 5 minutes'),
  ('BARRIO_PINTO', '18', array['no_paso_google_maps', 'no_hizo_parada'], now() - interval '710 hours 41 minutes');

insert into public.units (code, route, verified, source) values
  ('51', 'SAN_RAMON', false, 'development seed'),
  ('99', 'SAN_RAMON', false, 'development seed'),
  ('SJB123', 'SAN_RAMON', false, 'development seed'),
  ('24', 'LA_EUROPA', false, 'development seed'),
  ('CR4521', 'LA_EUROPA', false, 'development seed'),
  ('12', 'LA_CAMPINA', false, 'development seed'),
  ('33', 'GRANADILLA', false, 'development seed'),
  ('41', 'SABANILLA', false, 'development seed'),
  ('58', 'SALITRILLOS', false, 'development seed'),
  ('62', 'VARGAS_ARAYA', false, 'development seed'),
  ('77', 'BARRIO_PINTO', false, 'development seed'),
  ('84', 'CEDROS', false, 'development seed')
on conflict (code, route) do nothing;

